#pragma once

#include <cstddef>
#include <memory>
#include <memory_resource>
#include <span>
#include <system_error>
#include <vector>

#include <asio/ip/tcp.hpp>
#include <openssl/bio.h>
#include <openssl/ssl.h>

#include "ruvia/core/task.h"
#include "ruvia/core/task_scope.h"
#include "ruvia/core/worker_handle.h"
#include "ruvia/core/worker_signal.h"

namespace ruvia::detail {

// Activated after the CONNECT head has been flushed and before tunnel I/O starts.
// Only the TLS write BIO changes: Asio retains its read BIO and buffered input.
// Every ciphertext producer, including TLS control messages generated by reads,
// feeds one bounded queue and one socket writer. SSL_shutdown sends close_notify
// once; flush() waits for that alert without consuming the peer's remaining data.
class tls_tunnel_output final {
public:
    tls_tunnel_output(SSL& ssl, asio::ip::tcp::socket& socket, const worker_handle& worker_value,
        std::pmr::memory_resource& resource);
    ~tls_tunnel_output();
    tls_tunnel_output(const tls_tunnel_output&) = delete;
    tls_tunnel_output& operator=(const tls_tunnel_output&) = delete;
    void start();
    [[nodiscard]] task<std::error_code> flush();
    [[nodiscard]] task<std::error_code> finish();
    void abort() noexcept;
    [[nodiscard]] task<void> join();

private:
    static const std::unique_ptr<BIO_METHOD, decltype(&BIO_meth_free)> bio_method_;
    static int create_bio(BIO* bio) noexcept;
    static int destroy_bio(BIO* bio) noexcept;
    static int write_bio(BIO* bio, const char* bytes, std::size_t size, std::size_t* written) noexcept;
    static long control_bio(BIO*, int command, long, void*) noexcept;
    [[nodiscard]] task<void> run_writer();
    [[nodiscard]] task<void> run_writer_inner();
    void fail(std::error_code error) noexcept;

    SSL& ssl_;
    asio::ip::tcp::socket& socket_;
    const worker_handle& worker_;
    BIO* previous_{nullptr};
    std::pmr::vector<char> bytes_;
    std::size_t head_{0};
    std::size_t size_{0};
    std::error_code error_{};
    bool started_{false};
    bool stopping_{false};
    bool send_ended_{false};
    worker_signal available_;
    worker_signal flushed_;
    task_scope tasks_;
};

}  // namespace ruvia::detail
