#pragma once

#include <cstddef>
#include <memory>
#include <memory_resource>
#include <span>
#include <system_error>
#include <vector>

#include <asio/ip/tcp.hpp>
#include <openssl/bio.h>
#include <openssl/ssl.h>

#include "ruvia/core/Task.h"
#include "ruvia/core/TaskScope.h"
#include "ruvia/core/WorkerHandle.h"
#include "ruvia/core/WorkerSignal.h"

namespace ruvia::detail {

// Activated after the CONNECT head has been flushed and before tunnel I/O starts.
// Only the TLS write BIO changes: Asio retains its read BIO and buffered input.
// Every ciphertext producer, including TLS control messages generated by reads,
// feeds one bounded queue and one socket writer. SSL_shutdown sends close_notify
// once; flush() waits for that alert without consuming the peer's remaining data.
class TlsTunnelOutput final {
public:
    TlsTunnelOutput(SSL& ssl, asio::ip::tcp::socket& socket, const WorkerHandle& worker,
        std::pmr::memory_resource& resource);
    ~TlsTunnelOutput();
    TlsTunnelOutput(const TlsTunnelOutput&) = delete;
    TlsTunnelOutput& operator=(const TlsTunnelOutput&) = delete;
    void start();
    [[nodiscard]] Task<std::error_code> flush();
    [[nodiscard]] Task<std::error_code> finish();
    void abort() noexcept;
    [[nodiscard]] Task<void> join();

private:
    static const std::unique_ptr<BIO_METHOD, decltype(&BIO_meth_free)> bioMethod_;
    static int createBio(BIO* bio) noexcept;
    static int destroyBio(BIO* bio) noexcept;
    static int writeBio(BIO* bio, const char* bytes, int size) noexcept;
    static long controlBio(BIO*, int command, long, void*) noexcept;
    [[nodiscard]] Task<void> runWriter();
    [[nodiscard]] Task<void> runWriterInner();
    void fail(std::error_code error) noexcept;

    SSL& ssl_;
    asio::ip::tcp::socket& socket_;
    const WorkerHandle& worker_;
    BIO* previous_{nullptr};
    std::pmr::vector<char> bytes_;
    std::size_t head_{0};
    std::size_t size_{0};
    std::error_code error_{};
    bool started_{false};
    bool stopping_{false};
    bool sendEnded_{false};
    WorkerSignal available_;
    WorkerSignal flushed_;
    TaskScope tasks_;
};

}  // namespace ruvia::detail
