#pragma once
#include "ruvia/web/detail/model/ModelField.h"
#include "ruvia/web/detail/model/ModelSchema.h"
#include "ruvia/web/detail/model/macro/MacroCore.h"

// A field declaration lives directly inside a normal struct. The generated
// accessors deliberately preserve the existing Hono-style model call surface.

#define RUVIA_MODEL_DECLARE_FIELD(required, wire, field, type, ...)                                                                                                                                                                                                                                                                                               \
private:                                                                                                                                                                                                                                                                                                                                                          \
    using RuviaFieldType_##field = RUVIA_MODEL_UNPAREN type;                                                                                                                                                                                                                                                                                                      \
    using RuviaFieldOptions_##field = decltype(::ruvia::detail::model::ModelOptions{__VA_ARGS__});                                                                                                                                                                                                                                                                \
    static constexpr auto ruviaFieldWireHash_##field = ::ruvia::detail::model::modelFieldNameHash(::std::string_view{wire});                                                                                                                                                                                                                                      \
    ::ruvia::detail::model::ModelField<RuviaFieldType_##field, required, RuviaFieldOptions_##field> ruviaField_##field##_{wire, ::ruvia::detail::model::ModelOptions{__VA_ARGS__}};                                                                                                                                                                               \
                                                                                                                                                                                                                                                                                                                                                                  \
public:                                                                                                                                                                                                                                                                                                                                                           \
    [[nodiscard]] const ::std::optional<RuviaFieldType_##field>& field() const& noexcept {                                                                                                                                                                                                                                                                        \
        return ruviaField_##field##_.value();                                                                                                                                                                                                                                                                                                                     \
    }                                                                                                                                                                                                                                                                                                                                                             \
    [[nodiscard]] const ::std::optional<RuviaFieldType_##field>& field() const&& = delete;                                                                                                                                                                                                                                                                        \
    [[nodiscard]] RuviaFieldType_##field& field##Ensure() & {                                                                                                                                                                                                                                                                                                     \
        return ruviaField_##field##_.ensure(ruviaResource_);                                                                                                                                                                                                                                                                                                      \
    }                                                                                                                                                                                                                                                                                                                                                             \
    [[nodiscard]] RuviaFieldType_##field& field##Ensure() && = delete;                                                                                                                                                                                                                                                                                            \
    void field##Reset() noexcept {                                                                                                                                                                                                                                                                                                                                \
        ruviaField_##field##_.reset();                                                                                                                                                                                                                                                                                                                            \
    }                                                                                                                                                                                                                                                                                                                                                             \
    template <typename RuviaFieldValueT>                                                                                                                                                                                                                                                                                                                          \
        requires((::ruvia::detail::isRuviaString<RuviaFieldType_##field> && (::std::is_convertible_v<RuviaFieldValueT &&, ::std::string_view> || ::std::constructible_from<RuviaFieldType_##field, RuviaFieldValueT &&>)) || (!::ruvia::detail::isRuviaString<RuviaFieldType_##field> && ::std::constructible_from<RuviaFieldType_##field, RuviaFieldValueT &&>)) \
    auto& field(RuviaFieldValueT&& value) & {                                                                                                                                                                                                                                                                                                                     \
        ruviaField_##field##_.assign(::std::forward<RuviaFieldValueT>(value), ruviaResource_);                                                                                                                                                                                                                                                                    \
        return *this;                                                                                                                                                                                                                                                                                                                                             \
    }                                                                                                                                                                                                                                                                                                                                                             \
    template <typename RuviaFieldValueT>                                                                                                                                                                                                                                                                                                                          \
    auto& field(RuviaFieldValueT&&) && = delete;

#define RUVIA_FIELD(field, type, ...) RUVIA_MODEL_DECLARE_FIELD(true, #field, field, (type), __VA_ARGS__)

#define RUVIA_FIELD_NAME(wire_name, field, type, ...) RUVIA_MODEL_DECLARE_FIELD(true, wire_name, field, (type), __VA_ARGS__)

#define RUVIA_OPTIONAL_FIELD(field, type, ...) RUVIA_MODEL_DECLARE_FIELD(false, #field, field, (type), __VA_ARGS__)

#define RUVIA_OPTIONAL_FIELD_NAME(wire_name, field, type, ...) RUVIA_MODEL_DECLARE_FIELD(false, wire_name, field, (type), __VA_ARGS__)

#define RUVIA_MODEL_SCHEMA_FIELD(T, field)                                                                                                               \
    ::ruvia::detail::model::ModelFieldDescriptor<&T::ruviaField_##field##_, T::ruviaFieldWireHash_##field, ::ruvia::FixedString{#field}>{},
