#pragma once

#include <cstdint>
#include <string_view>
#include <type_traits>
#include <utility>

#include "ruvia/web/detail/model/Traits.h"

namespace ruvia::detail::model {

// One descriptor per declared field is generated by RUVIA_MODEL. Operations
// consume this schema instead of expanding the user-provided field list again
// for parsing, serialization, defaults, and validation.
template <auto Member, std::uint64_t WireHash, FixedString SourceName>
struct ModelFieldDescriptor final {
    static constexpr auto member = Member;
    static constexpr auto wireHash = WireHash;
    static constexpr auto sourceName = SourceName;

    template <typename ModelT>
    [[nodiscard]] static constexpr decltype(auto) get(ModelT&& model) noexcept {
        return std::forward<ModelT>(model).*member;
    }
};

template <typename... DescriptorTs>
struct ModelSchema final {
    constexpr explicit ModelSchema(DescriptorTs...) noexcept {}
};

template <typename... DescriptorTs>
ModelSchema(DescriptorTs...) -> ModelSchema<DescriptorTs...>;

template <typename ModelT, typename... DescriptorTs, typename VisitorT>
constexpr void visitModelFields(
    ModelT& model,
    ModelSchema<DescriptorTs...>,
    VisitorT&& visitor) {
    auto& visitorRef = visitor;
    (visitorRef(DescriptorTs{}, DescriptorTs::get(model)), ...);
}

template <typename ModelT, typename... DescriptorTs, typename VisitorT>
[[nodiscard]] bool visitModelFieldByWireName(
    ModelT& model,
    ModelSchema<DescriptorTs...>,
    std::uint64_t wireHash,
    std::string_view wireName,
    bool& visitResult,
    VisitorT&& visitor) {
    auto& visitorRef = visitor;
    const auto tryField = [&]<typename DescriptorT>() {
        auto& field = DescriptorT::get(model);
        if (wireHash != DescriptorT::wireHash || wireName != field.wireName()) {
            return false;
        }
        visitResult = visitorRef(field);
        return true;
    };
    return (tryField.template operator()<DescriptorTs>() || ...);
}

template <FixedString Field, typename SchemaT>
struct ModelSchemaContainsField;

template <FixedString Field, typename... DescriptorTs>
struct ModelSchemaContainsField<Field, ModelSchema<DescriptorTs...>>
    : std::bool_constant<((Field == DescriptorTs::sourceName) || ...)> {};

template <FixedString Field, typename ModelT, typename SchemaT>
[[nodiscard]] ModelFieldState modelFieldState(const ModelT& model, const SchemaT& schema) {
    using Schema = std::remove_cvref_t<SchemaT>;
    static_assert(ModelSchemaContainsField<Field, Schema>::value, "unknown RUVIA_MODEL field");

    ModelFieldState result = ModelFieldState::kMissing;
    visitModelFields(model, schema, [&]<typename DescriptorT>(const DescriptorT&, const auto& field) {
        if constexpr (Field == DescriptorT::sourceName) {
            result = field.state();
        }
    });
    return result;
}

}  // namespace ruvia::detail::model
