#include "ruvia/web/detail/server/HttpServer.h"
#include "ruvia/web/detail/server/request/RequestMemoryArena.h"
#include "ruvia/web/detail/server/request/HttpServerRequestState.h"
#include "ruvia/web/detail/server/tls/HttpServerAlpn.h"

#include <asio/ssl.hpp>
#include <openssl/bio.h>
#include <openssl/x509.h>
#include <array>
#include <cstring>
#include <memory>
#include <stdexcept>
#include <type_traits>
#include "ruvia/http/detail/request/HttpRequestAccess.h"
#include "ruvia/web/detail/server/http1/Http1SessionRequestCompletion.h"
#include "ruvia/web/detail/server/http1/Http1ClosingRejection.h"
#include "ruvia/web/detail/server/response/HttpBufferedResponse.h"
#include "ruvia/web/detail/server/response/HttpResponseWriter.h"
#include "ruvia/web/detail/server/HttpServerAccessLog.h"
#include "ruvia/web/detail/server/tls/HttpServerAutoHttps.h"
#include "ruvia/web/detail/server/route/HttpServerBodyRouteCompletion.h"
#include "ruvia/web/detail/http2/CleartextUpgrade.h"
#include "ruvia/web/detail/server/session/HttpServerConnectionGuards.h"
#include "ruvia/web/detail/server/session/HttpServerIdleWorkSet.h"
#include "ruvia/web/detail/server/session/HttpServerSessionEntry.h"
#include "ruvia/web/detail/server/session/HttpServerStreamSession.h"
#include "ruvia/web/detail/server/tls/HttpServerTlsHandshake.h"
#include "ruvia/web/detail/server/response/HttpServerResponseState.h"
#include "ruvia/web/detail/server/stream/HttpServerResponseStreamRoute.h"
#include "ruvia/web/detail/server/route/HttpServerStreamBodyRoute.h"
#include "ruvia/web/detail/server/route/HttpServerWebSocketRoute.h"
#include "ruvia/http/detail/http1/Http1ServerRequestParser.h"
#include "ruvia/http/detail/util/PmrString.h"
#include "ruvia/core/detail/io/AsioAwait.h"
#include "ruvia/core/detail/io/SocketUtils.h"

