cmake_minimum_required(VERSION 3.28)

if(kind STREQUAL "patch-postgresql")
    # Upstream's automatic dependency lookup can fall back to system OpenSSL.
    # Require our isolated pkg-config metadata instead; never search elsewhere.
    file(READ "${source}/meson.build" meson_build)
    set(original "ssl = dependency('openssl', required: false)")
    set(replacement "ssl = dependency('openssl', required: true, method: 'pkg-config', static: true)")
    string(FIND "${meson_build}" "${original}" found)
    if(found EQUAL -1)
        string(FIND "${meson_build}" "${replacement}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "PostgreSQL OpenSSL dependency declaration has changed")
        endif()
    else()
        string(REPLACE "${original}" "${replacement}" meson_build "${meson_build}")
        file(WRITE "${source}/meson.build" "${meson_build}")
    endif()
    return()
endif()

set(prefix "${root}/${config}")
set(binary "${prefix}/build")
file(MAKE_DIRECTORY "${binary}" "${prefix}/include" "${prefix}/lib")
if(WIN32)
    # MSBuild's pipe bypasses stdout/stderr, breaking Meson's /showIncludes probe.
    unset(ENV{VS_UNICODE_OUTPUT})
    set(ENV{CL} "/FS")
    unset(ENV{_CL_})
    get_filename_component(compiler_dir "${compiler}" DIRECTORY)
    set(ENV{PATH} "${compiler_dir};$ENV{PATH}")
endif()

function(run)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${binary}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()

function(copy_library source_name destination_name)
    file(COPY_FILE "${source_name}"
        "${prefix}/lib/${library_prefix}${destination_name}${library_suffix}" ONLY_IF_DIFFERENT)
endfunction()

function(configure_openssl)
    string(JOIN ";" signature ${ARGV} "$ENV{CC}" "$ENV{CL}" "$ENV{_CL_}")
    set(signature_file "${binary}/ruvia-configure.txt")
    if(EXISTS "${signature_file}")
        file(READ "${signature_file}" previous_signature)
    endif()
    if(NOT signature STREQUAL previous_signature)
        run(${ARGV})
        file(WRITE "${signature_file}" "${signature}")
    endif()
endfunction()

if(kind STREQUAL "openssl")
    if(WIN32)
        if(config STREQUAL "Debug")
            set(ENV{_CL_} "/MTd")
        else()
            set(ENV{_CL_} "/MT")
        endif()
    endif()
    set(options no-shared no-tests no-apps no-docs no-module --libdir=lib "--prefix=${prefix}")
    if(config STREQUAL "Debug")
        list(APPEND options --debug)
    endif()
    if(WIN32)
        if(NOT nasm)
            list(APPEND options no-asm)
        endif()
        configure_openssl("${perl}" "${source}/Configure" ${openssl_target} ${options})
        run("${make}" /NOLOGO "-j${jobs}" build_libs)
        run("${make}" /NOLOGO install_dev)
        copy_library("${prefix}/lib/libssl.lib" openssl_ssl)
        copy_library("${prefix}/lib/libcrypto.lib" openssl_crypto)
    else()
        set(ENV{CC} "${compiler}")
        configure_openssl("${perl}" "${source}/Configure" ${options} -fPIC)
        run("${make}" "-j${jobs}" build_libs)
        run("${make}" "-j${jobs}" install_dev)
        copy_library("${prefix}/lib/libssl.a" openssl_ssl)
        copy_library("${prefix}/lib/libcrypto.a" openssl_crypto)
    endif()
elseif(kind STREQUAL "mariadb")
    set(ssl "${openssl_root}/${config}")
    foreach(library IN ITEMS openssl_ssl openssl_crypto)
        set(${library} "${ssl}/lib/${library_prefix}${library}${library_suffix}")
        if(NOT EXISTS "${${library}}")
            message(FATAL_ERROR "Fetched OpenSSL library is missing: ${${library}}")
        endif()
    endforeach()
    if(NOT EXISTS "${zlib_library}")
        message(FATAL_ERROR "Fetched zlib library is missing: ${zlib_library}")
    endif()
    set(zlib_include "${binary}/ruvia-zlib/include")
    file(MAKE_DIRECTORY "${zlib_include}")
    file(COPY "${zlib_source}/zlib.h" "${zlib_binary}/zconf.h" DESTINATION "${zlib_include}")
    set(args -S "${source}" -B "${binary}" -G "${generator}"
        "-DCMAKE_BUILD_TYPE=${config}" "-DCMAKE_C_COMPILER=${compiler}"
        "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>"
        -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF
        -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=OFF -DCMAKE_DISABLE_FIND_PACKAGE_CURL=ON
        -DWITH_UNIT_TESTS=OFF -DWITH_TOOLS=OFF -DWITH_CURL=OFF -DWITH_ICONV=OFF
        -DWITH_EXTERNAL_ZLIB=ON "-DZLIB_INCLUDE_DIR=${zlib_include}"
        "-DZLIB_LIBRARY=${zlib_library}"
        -DZSTD_LIBRARIES:FILEPATH= -DZSTD_INCLUDE_DIRS:PATH=
        -DWITH_SSL=OPENSSL "-DOPENSSL_INCLUDE_DIR=${ssl}/include"
        "-DOPENSSL_SSL_LIBRARY=${openssl_ssl}" "-DOPENSSL_CRYPTO_LIBRARY=${openssl_crypto}"
        -DCLIENT_PLUGIN_AUTH_GSSAPI_CLIENT=OFF
        -DCLIENT_PLUGIN_REMOTE_IO=OFF
        -DCLIENT_PLUGIN_CACHING_SHA2_PASSWORD=STATIC -DCLIENT_PLUGIN_SHA256_PASSWORD=STATIC
        -DCLIENT_PLUGIN_MYSQL_CLEAR_PASSWORD=STATIC -DCLIENT_PLUGIN_DIALOG=STATIC
        -DOPENSSL_VERSION=4.0.3 -DZSTD_LIBRARY= -DZSTD_INCLUDE_DIR=)
    if(WIN32)
        list(APPEND args -DCMAKE_POLICY_DEFAULT_CMP0091=NEW)
    endif()
    if(platform)
        list(APPEND args -A "${platform}")
    endif()
    if(toolset)
        list(APPEND args -T "${toolset}")
    endif()
    run("${CMAKE_COMMAND}" ${args})
    run("${CMAKE_COMMAND}" --build "${binary}" --config "${config}" --target mariadbclient "-j${jobs}")
    if(WIN32)
        file(GLOB_RECURSE libraries "${binary}/*mariadbclient.lib")
    else()
        file(GLOB_RECURSE libraries "${binary}/*mariadbclient.a")
    endif()
    list(LENGTH libraries count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one MariaDB static library, found: ${libraries}")
    endif()
    list(GET libraries 0 library)
    copy_library("${library}" mariadb_client)
    file(COPY "${source}/include/" DESTINATION "${prefix}/include" FILES_MATCHING PATTERN "*.h")
    file(COPY "${binary}/include/" DESTINATION "${prefix}/include" FILES_MATCHING PATTERN "*.h")
elseif(kind STREQUAL "postgresql")
    set(ssl "${openssl_root}/${config}")
    set(pkgconfig_dir "${binary}/ruvia-pkgconfig")
    file(MAKE_DIRECTORY "${pkgconfig_dir}")
    file(STRINGS "${ssl}/include/openssl/opensslv.h" version_line
        REGEX "^# *define OPENSSL_VERSION_STR ")
    if(NOT version_line MATCHES "\"([0-9]+\\.[0-9]+\\.[0-9]+)\"")
        message(FATAL_ERROR "Cannot read fetched OpenSSL version")
    endif()
    set(ssl_version "${CMAKE_MATCH_1}")
    set(ssl_library "${ssl}/lib/${library_prefix}openssl_ssl${library_suffix}")
    set(crypto_library "${ssl}/lib/${library_prefix}openssl_crypto${library_suffix}")
    foreach(library IN ITEMS "${ssl_library}" "${crypto_library}")
        if(NOT EXISTS "${library}")
            message(FATAL_ERROR "Fetched OpenSSL library is missing: ${library}")
        endif()
    endforeach()
    if(WIN32)
        set(ssl_platform_libs "ws2_32.lib crypt32.lib advapi32.lib user32.lib")
    else()
        set(ssl_platform_libs "-pthread -lm")
        if(dl_library)
            string(APPEND ssl_platform_libs " -l${dl_library}")
        endif()
    endif()
    file(WRITE "${pkgconfig_dir}/openssl.pc"
        "Name: Ruvia fetched OpenSSL\nDescription: FetchContent static OpenSSL\nVersion: ${ssl_version}\nLibs: \"${ssl_library}\" \"${crypto_library}\" ${ssl_platform_libs}\nCflags: -I\"${ssl}/include\"\n")
    # Both pkg-config search paths are private, including when nested in a
    # consumer using vcpkg or another package manager.
    set(ENV{PKG_CONFIG_PATH} "")
    set(ENV{PKG_CONFIG_LIBDIR} "${pkgconfig_dir}")
    set(ENV{PKG_CONFIG_SYSROOT_DIR} "")
    set(ENV{NINJA} "${ninja}")
    file(WRITE "${binary}/ruvia-native.ini"
        "[binaries]\nc = ['${compiler}']\nar = ['${archiver}']\npkg-config = ['${pkgconfig}']\n")
    set(options --backend=ninja --wrap-mode=nofallback
        "--native-file=${binary}/ruvia-native.ini"
        -Dauto_features=disabled -Dssl=openssl -Dzlib=disabled -Ddefault_library=static
        -Db_staticpic=true "-Dpkg_config_path=[]" "-DPERL=${perl}"
        "-DBISON=['${bison}']" "-DFLEX=['${flex}']")
    if(config STREQUAL "Debug")
        list(APPEND options --buildtype=debug)
    elseif(config STREQUAL "RelWithDebInfo")
        list(APPEND options --buildtype=debugoptimized)
    elseif(config STREQUAL "MinSizeRel")
        list(APPEND options --buildtype=minsize)
    else()
        list(APPEND options --buildtype=release)
    endif()
    if(WIN32)
        list(APPEND options "-Dc_link_args=['ws2_32.lib','crypt32.lib','advapi32.lib','user32.lib']")
        if(config STREQUAL "Debug")
            list(APPEND options -Db_vscrt=mtd)
        else()
            list(APPEND options -Db_vscrt=mt)
        endif()
    endif()
    if(EXISTS "${binary}/meson-private/coredata.dat")
        set(reconfigure --reconfigure --clearcache)
    endif()
    run("${meson}" setup ${reconfigure} "${binary}" "${source}" ${options})
    # libpq exposes the public encoding functions. The common archive built
    # for shared-library code retains those names; the ordinary frontend
    # archive renames them to *_private. Both archives are static libraries.
    run("${meson}" compile -C "${binary}" "-j${jobs}" libpq:static_library libpgcommon_shlib:static_library libpgport:static_library libpgcommon_excluded_shlib:static_library)
    file(READ "${binary}/meson-info/intro-targets.json" targets)
    string(JSON count LENGTH "${targets}")
    set(missing postgresql_client postgresql_common postgresql_port postgresql_frontend)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
        string(JSON name GET "${targets}" ${index} name)
        string(JSON type GET "${targets}" ${index} type)
        if(type STREQUAL "static library")
            if(name STREQUAL "libpq")
                set(destination postgresql_client)
            elseif(name STREQUAL "libpgcommon_shlib")
                set(destination postgresql_common)
            elseif(name STREQUAL "libpgport")
                set(destination postgresql_port)
            elseif(name STREQUAL "libpgcommon_excluded_shlib")
                set(destination postgresql_frontend)
            else()
                continue()
            endif()
            string(JSON library GET "${targets}" ${index} filename 0)
            copy_library("${library}" "${destination}")
            list(REMOVE_ITEM missing "${destination}")
        endif()
    endforeach()
    if(missing)
        message(FATAL_ERROR "PostgreSQL static libraries were not produced: ${missing}")
    endif()
    file(COPY "${source}/src/interfaces/libpq/libpq-fe.h"
        "${source}/src/interfaces/libpq/libpq-events.h"
        "${source}/src/include/postgres_ext.h" DESTINATION "${prefix}/include")
else()
    message(FATAL_ERROR "Unknown native dependency: ${kind}")
endif()

file(TOUCH "${prefix}/complete.stamp")
