cmake_minimum_required(VERSION 3.28)

set(prefix "${root}/${config}")
set(binary "${prefix}/build")
file(MAKE_DIRECTORY "${binary}" "${prefix}/include" "${prefix}/lib")
if(WIN32)
    set(ENV{CL} "$ENV{CL} /FS")
endif()

function(run)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${binary}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()

function(copy_library source_name destination_name)
    file(COPY_FILE "${source_name}"
        "${prefix}/lib/${library_prefix}${destination_name}${library_suffix}" ONLY_IF_DIFFERENT)
endfunction()

function(configure_openssl)
    string(JOIN ";" signature ${ARGV} "$ENV{CC}" "$ENV{_CL_}")
    set(signature_file "${binary}/ruvia-configure.txt")
    if(EXISTS "${signature_file}")
        file(READ "${signature_file}" previous_signature)
    endif()
    if(NOT signature STREQUAL previous_signature)
        run(${ARGV})
        file(WRITE "${signature_file}" "${signature}")
    endif()
endfunction()

if(kind STREQUAL "openssl")
    if(WIN32)
        if(config STREQUAL "Debug")
            set(ENV{_CL_} "$ENV{_CL_} /MTd")
        else()
            set(ENV{_CL_} "$ENV{_CL_} /MT")
        endif()
    endif()
    set(options no-shared no-tests no-apps no-docs no-module --libdir=lib "--prefix=${prefix}")
    if(config STREQUAL "Debug")
        list(APPEND options --debug)
    endif()
    if(WIN32)
        find_program(nasm NAMES nasm)
        if(NOT nasm)
            list(APPEND options no-asm)
        endif()
        configure_openssl("${perl}" "${source}/Configure" ${openssl_target} ${options})
        run("${make}" /NOLOGO "-j${jobs}" build_libs)
        run("${make}" /NOLOGO install_dev)
        copy_library("${prefix}/lib/libssl.lib" openssl_ssl)
        copy_library("${prefix}/lib/libcrypto.lib" openssl_crypto)
    else()
        set(ENV{CC} "${compiler}")
        configure_openssl("${perl}" "${source}/Configure" ${options} -fPIC)
        run("${make}" "-j${jobs}" build_libs)
        run("${make}" "-j${jobs}" install_dev)
        copy_library("${prefix}/lib/libssl.a" openssl_ssl)
        copy_library("${prefix}/lib/libcrypto.a" openssl_crypto)
    endif()
elseif(kind STREQUAL "mariadb")
    set(ssl "${openssl_root}/${config}")
    set(args -S "${source}" -B "${binary}" -G "${generator}"
        "-DCMAKE_BUILD_TYPE=${config}" "-DCMAKE_C_COMPILER=${compiler}"
        "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>"
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DWITH_UNIT_TESTS=OFF -DWITH_TOOLS=OFF -DWITH_CURL=OFF
        -DWITH_EXTERNAL_ZLIB=ON "-DZLIB_INCLUDE_DIR=${zlib_include}" "-DZLIB_LIBRARY=${zlib_library}"
        -DWITH_SSL=OPENSSL "-DOPENSSL_ROOT_DIR=${ssl}" -DOPENSSL_USE_STATIC_LIBS=ON
        -DCLIENT_PLUGIN_AUTH_GSSAPI=OFF -DCLIENT_PLUGIN_REMOTEIO=OFF
        -DCLIENT_PLUGIN_CACHING_SHA2_PASSWORD=STATIC -DCLIENT_PLUGIN_SHA256_PASSWORD=STATIC
        -DCLIENT_PLUGIN_MYSQL_CLEAR_PASSWORD=STATIC -DCLIENT_PLUGIN_DIALOG=STATIC
        -DCLIENT_PLUGIN_CLIENT_ED25519=STATIC -DCLIENT_PLUGIN_ZSTD=OFF)
    if(platform)
        list(APPEND args -A "${platform}")
    endif()
    run("${CMAKE_COMMAND}" ${args})
    run("${CMAKE_COMMAND}" --build "${binary}" --config "${config}" --target mariadbclient "-j${jobs}")
    if(WIN32)
        file(GLOB_RECURSE libraries "${binary}/*mariadbclient.lib")
    else()
        file(GLOB_RECURSE libraries "${binary}/*mariadbclient.a")
    endif()
    list(LENGTH libraries count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one MariaDB static library, found: ${libraries}")
    endif()
    list(GET libraries 0 library)
    copy_library("${library}" mariadb_client)
    file(COPY "${source}/include/" DESTINATION "${prefix}/include" FILES_MATCHING PATTERN "*.h")
    file(COPY "${binary}/include/" DESTINATION "${prefix}/include" FILES_MATCHING PATTERN "*.h")
elseif(kind STREQUAL "postgresql")
    set(ssl "${openssl_root}/${config}")
    set(options -Dauto_features=disabled -Dssl=openssl -Ddefault_library=static
        -Dextra_include_dirs=${ssl}/include -Dextra_lib_dirs=${ssl}/lib "-DPERL=${perl}")
    if(config STREQUAL "Debug")
        list(APPEND options --buildtype=debug)
    else()
        list(APPEND options --buildtype=release)
    endif()
    if(WIN32)
        list(APPEND options "-Dc_link_args=['ws2_32.lib','crypt32.lib','advapi32.lib','user32.lib']")
        if(config STREQUAL "Debug")
            list(APPEND options -Db_vscrt=mtd)
        else()
            list(APPEND options -Db_vscrt=mt)
        endif()
    endif()
    if(EXISTS "${binary}/meson-private/coredata.dat")
        set(reconfigure --reconfigure)
    endif()
    run("${meson}" setup ${reconfigure} "${binary}" "${source}" ${options})
    # libpq exposes the public encoding functions. The common archive built
    # for shared-library code retains those names; the ordinary frontend
    # archive renames them to *_private. Both archives are static libraries.
    run("${meson}" compile -C "${binary}" "-j${jobs}" libpq:static_library libpgcommon_shlib:static_library libpgport:static_library libpgcommon_excluded_shlib:static_library)
    file(READ "${binary}/meson-info/intro-targets.json" targets)
    string(JSON count LENGTH "${targets}")
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
        string(JSON name GET "${targets}" ${index} name)
        string(JSON type GET "${targets}" ${index} type)
        if(type STREQUAL "static library")
            if(name STREQUAL "libpq")
                set(destination postgresql_client)
            elseif(name STREQUAL "libpgcommon_shlib")
                set(destination postgresql_common)
            elseif(name STREQUAL "libpgport")
                set(destination postgresql_port)
            elseif(name STREQUAL "libpgcommon_excluded_shlib")
                set(destination postgresql_frontend)
            else()
                continue()
            endif()
            string(JSON library GET "${targets}" ${index} filename 0)
            copy_library("${library}" "${destination}")
        endif()
    endforeach()
    file(COPY "${source}/src/interfaces/libpq/libpq-fe.h"
        "${source}/src/interfaces/libpq/libpq-events.h"
        "${source}/src/include/postgres_ext.h" DESTINATION "${prefix}/include")
else()
    message(FATAL_ERROR "Unknown native dependency: ${kind}")
endif()

file(TOUCH "${prefix}/complete.stamp")
